### ISSUE TITLE
No MySQL databases available.

### ISSUE THREAD

**Issue by eruvanos** [andreasf/cf-mysql-plugin#3] opened 2016-12-06 08:08 UTC
In my space I have two databases connected to a go app, which is called test-app.

Dbs:
* db
* db2

Both are bound to the test-app. Env of app looks like:

```
System-Provided:
{
 "VCAP_SERVICES": {
  "mysql-dev": [
   {
    "credentials": {
     "hostname": "someHostname",
     "jdbcUrl": "jdbc:mysql://someHostname:3306/cf_xxxxx?user=xxxx\u0026password=xxxx",
     "name": "xxxx",
     "password": "xxxx",
     "port": 3306,
     "uri": "mysql://xxxx:xxxxx@someHostname:3306/dbname?reconnect=true",
     "username": "xxxx"
    },
    "label": "mysql-dev",
    "name": "db",
    "plan": "shared",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "mysql",
     "aws",
     "rds",
     "shared",
     "development"
    ],
    "volume_mounts": []
   }
  ]
 }
}
```

**Comment by andreasf** [comment] 2016-12-07 09:40
Thanks for reporting!

After checking the output of `cf curl` in your space, we determined that this is a duplicate of #2 .

**Closed as completed** 2016-12-07 09:42 UTC
Labels: duplicate
